services:
  - type: web
    name: swiftmyday-parse-server
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: PARSE_MOUNT
        value: "/parse"
      - key: APP_ID
        generateValue: true
      - key: MASTER_KEY
        generateValue: true
      - key: SERVER_URL
        value: "http://your-render-app-url/parse"
      - key: DATABASE_URI
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false
